version: '3'

services:
  database:
    image: mariadb:10.11.2
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  database_data:
